version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 419098763834.dkr.ecr.us-east-1.amazonaws.com
      - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.19.0/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - pwd 
      - ls
      - ./kubectl version --client
      - apt-get update
      - apt-get install postgresql-client -y
      - apt-get install bc -
      - echo $PGDATABASE
      - chmod +x db-integration.sh
      - ./db-integration.sh
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME:$K8_NAMESPACE-$CODEBUILD_BUILD_NUMBER .
      - docker tag $IMAGE_REPO_NAME:$K8_NAMESPACE-$CODEBUILD_BUILD_NUMBER 419098763834.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME:$K8_NAMESPACE-$CODEBUILD_BUILD_NUMBER      
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 419098763834.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME:$K8_NAMESPACE-$CODEBUILD_BUILD_NUMBER

  post_build:
    commands:
      - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_NEW
      - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_NEW
      - export AWS_DEFAULT_REGION=us-east-1
      - aws eks update-kubeconfig --name eks-dev-amplify --region us-east-1
      - ./kubectl set image deployment appointment appointment=419098763834.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME:$K8_NAMESPACE-$CODEBUILD_BUILD_NUMBER -n $K8_NAMESPACE
